name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bauv-client:$(date +%s)
    
    - name: Extract Docker image
      run: docker save bauv-client:latest | gzip > bauv-client.tar.gz 
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: bauv-client.tar.gz

